### ISSUE TITLE
COMPILE ERROR Undefined variable `NSIsModEnabled`

### ISSUE THREAD

**Issue by NachosChipeados** [Dinorush/Brute4#16]
Northstar 1.29.0 changed the way we get mod information and removed `NsIsModEnabled` in the process. Now the mod creates a script error on startup

![image](https://github.com/user-attachments/assets/ebd75cb3-b0b6-4792-a465-e111f88c1dac)

**Comment by Dinorush** [comment]
Resolved in 1.8.14 by 293f3b0855b5d48f7a7bb772c689b2ce91973f8f.
